const Products = () => {
    return (
        <>
        <div style={{display:"flex", justifyContent:"center",backgroundColor:"gray",margin:"5px"}}>
            <h3 style={{textAlign:"center"}}>Take a look at our medical supplies and 
                contact us if you find what you are looking for, or better still 
                contact us to get quotations and more information.
            </h3>
        </div>
        <section id="prod-container" className="holder">
            <div className="products">
                <img src="./images/xray.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>X-RAY MACHINE</h4>
                    <p>ECG records the electrical activity generated by heart muscle depolarization, which propagate in pulsating electrical waves towards the skin. ECG electrodes are typically wet sensors, requiring the use of a conductive gel to increase conductivity between skin and electrodes</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/sono.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>SONOGRAPH</h4>
                    <p>Diagnostic sonography (ultrasonography) is an ultrasound-based diagnostic imaging technique used to visualize subcutaneous body structures including tendons, muscles, joints, vessels and internal organs for possible pathology or lesions.</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/face_shield.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>FACE SHIELD</h4>
                    <p>An item of personal protective equipment, aims to protect the wearer’s entire face from hazards such as flying objects and road debris, chemical splashes, or potentially infectious materials.</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/ortho.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>ORTHOPAEDIC HARDWARE</h4>
                    <p>All modern models are in stock</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/gowns.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>DISPOSAL GOWNS</h4>
                    <p>Non-sterile, disposable patient isolation gowns, which are used for routine patient care in healthcare settings, are appropriate for use by HCP when caring for patients with suspected or confirmed COVID-19.</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/sonyupp.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>ECG MACHINE</h4>
                    <p>Sony thermal print media.High Gloss thermal recording papers are widely used for Ultrasound systems for printing high-resolution ultrasound images..</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/feet_ppes.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>ECG MACHINE</h4>
                    <p>Disposable Protective kits for the feet.</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/digitherm.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>DIGITAL THERMOMETER</h4>
                    <p>A thermometer is a device that measures temperature or a temperature gradient A thermometer has two important elements: a temperature sensor in which some change occurs with a change in temperature; and some means of converting this change into a numerical value</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/ultra_gel.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>ULTRASOUND GEL</h4>
                    <p>Ultrasound gel is a conductive medium that creates a bond between the skin and the ultrasound transducer.</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/test_kits.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>EDTA TEST KITS</h4>
                    <p>EDTA stands for Ethylenediaminetetraacetic acid. EDTA functions by binding calcium in the blood and keeping the blood from clotting. BD Vacutainer Plus Blood Collection Tubes contain K2EDTA, which is spray-dried to the walls of the tube.</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/gauze_cotton.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>GAUZE/ABSORBENT COTTON</h4>
                    <p>Used for holding other wound dressings in place, gauze rolls can be wrapped around the body and secured with medical tape. Gauze rolls can be cotton, elastic, or nylon and latex mix, the pattern tends to be fluff dried with crinkle-weave.</p>
                </div>

            </div>
            <div className="products">
                <img src="./images/ecg.jpg" alt="prod"/>
                <div className="prod-text">
                    <h4>ECG MACHINE</h4>
                    <p>ECG records the electrical activity generated by heart muscle depolarization, which propagate in pulsating electrical waves towards the skin. ECG electrodes are typically wet sensors, requiring the use of a conductive gel to increase conductivity between skin and electrodes</p>
                </div>

            </div>
            
        </section>
        </>
    )
}

export default Products
